/* SAM2 Python Reference Comparison Tests */
/* Copyright 2025 AXELL CORPORATION and ax Inc. */
/*
 * These tests compare C# SAM2 processing output against exact numerical
 * values computed by the Python SAM2 reference implementation.
 *
 * Ground truth generated by: generate_sam2_reference.py
 * Python SAM2 source:
 *   - sam2/modeling/sam2_base.py: pixel_mean=[123.675, 116.28, 103.53]/255
 *                                 pixel_std=[58.395, 57.12, 57.375]/255
 *   - sam2/sam2_image_predictor.py: _transforms(), set_image()
 *   - Preprocessing: img / 255.0 -> (val - mean) / std -> CHW
 *   - Coordinate: coords * 1024 / original_size
 *   - Mask: bilinear resize -> threshold > 0.0
 */

using NUnit.Framework;
using System;
using UnityEngine;

[TestFixture]
public class PythonComparisonTest
{
    private Sam2InferenceEngine logic = null!;

    // Tolerance for float comparison between Python and C#
    // Python uses float64 by default; C# uses float32.
    // 1e-4 accounts for float32 precision difference.
    private const float Tol = 1e-4f;

    [SetUp]
    public void SetUp()
    {
        logic = new Sam2InferenceEngine();
    }

    // =======================================================
    // Python ground truth values (from generate_sam2_reference.py)
    //
    // pixel_mean = [123.675, 116.28, 103.53] / 255.0
    // pixel_std  = [58.395, 57.12, 57.375] / 255.0
    // =======================================================

    // -----------------------------------------------------------
    // 1. Single pixel normalization vs Python
    //    Python: (np.array([128,64,192])/255.0 - mean) / std
    //    Result: R=0.07406469, G=-0.91526604, B=1.54196085
    // -----------------------------------------------------------
    [Test]
    public void Python_SinglePixel_Normalization()
    {
        Color32[] pixel = new Color32[] { new Color32(128, 64, 192, 255) };
        float[,,,] result = logic.PreprocessImage(pixel, 1, 1, 1);

        // Python exact values
        Assert.That(result[0, 0, 0, 0], Is.EqualTo(0.07406469f).Within(Tol),
            "R: C# vs Python(0.07406469)");
        Assert.That(result[0, 1, 0, 0], Is.EqualTo(-0.91526604f).Within(Tol),
            "G: C# vs Python(-0.91526604)");
        Assert.That(result[0, 2, 0, 0], Is.EqualTo(1.54196085f).Within(Tol),
            "B: C# vs Python(1.54196085)");
    }

    // -----------------------------------------------------------
    // 2. Black pixel normalization vs Python
    //    Python: (0 - mean) / std
    //    Result: R=-2.11790393, G=-2.03571429, B=-1.80444444
    // -----------------------------------------------------------
    [Test]
    public void Python_BlackPixel_Normalization()
    {
        Color32[] pixel = new Color32[] { new Color32(0, 0, 0, 255) };
        float[,,,] result = logic.PreprocessImage(pixel, 1, 1, 1);

        Assert.That(result[0, 0, 0, 0], Is.EqualTo(-2.11790393f).Within(Tol),
            "R: C# vs Python(-2.11790393)");
        Assert.That(result[0, 1, 0, 0], Is.EqualTo(-2.03571429f).Within(Tol),
            "G: C# vs Python(-2.03571429)");
        Assert.That(result[0, 2, 0, 0], Is.EqualTo(-1.80444444f).Within(Tol),
            "B: C# vs Python(-1.80444444)");
    }

    // -----------------------------------------------------------
    // 3. White pixel normalization vs Python
    //    Python: (1.0 - mean) / std
    //    Result: R=2.24890830, G=2.42857143, B=2.64000000
    // -----------------------------------------------------------
    [Test]
    public void Python_WhitePixel_Normalization()
    {
        Color32[] pixel = new Color32[] { new Color32(255, 255, 255, 255) };
        float[,,,] result = logic.PreprocessImage(pixel, 1, 1, 1);

        Assert.That(result[0, 0, 0, 0], Is.EqualTo(2.24890830f).Within(Tol),
            "R: C# vs Python(2.24890830)");
        Assert.That(result[0, 1, 0, 0], Is.EqualTo(2.42857143f).Within(Tol),
            "G: C# vs Python(2.42857143)");
        Assert.That(result[0, 2, 0, 0], Is.EqualTo(2.64000000f).Within(Tol),
            "B: C# vs Python(2.64000000)");
    }

    // -----------------------------------------------------------
    // 4. 2x3 image normalization vs Python (full CHW comparison)
    //    Python input: [[100,150,200],[50,100,150],[200,50,100]],
    //                  [[10,20,30],[255,128,64],[0,255,0]]
    //    Python output CHW (3, 2, 3):
    //      Ch0: [[-0.40542852, -1.26166622,  1.30704689],
    //            [-1.94665639,  2.24890830, -2.11790393]]
    //      Ch1: [[ 0.59033624, -0.28501398, -1.16036413],
    //            [-1.68557422,  0.20518221,  2.42857143]]
    //      Ch2: [[ 1.68139439,  0.80993475, -0.06152503],
    //            [-1.28156863, -0.68897597, -1.80444444]]
    // -----------------------------------------------------------
    [Test]
    public void Python_2x3Image_FullCHW_Comparison()
    {
        // Build 2x3 image (H=2, W=3)
        // Row 0: (100,150,200), (50,100,150), (200,50,100)
        // Row 1: (10,20,30), (255,128,64), (0,255,0)
        Color32[] pixels = new Color32[]
        {
            new Color32(100, 150, 200, 255),
            new Color32(50, 100, 150, 255),
            new Color32(200, 50, 100, 255),
            new Color32(10, 20, 30, 255),
            new Color32(255, 128, 64, 255),
            new Color32(0, 255, 0, 255),
        };

        // PreprocessImage with imageSize=3 would resize, so we test
        // the normalization steps directly to match Python exactly
        float[,,] floatImg = Sam2TestHelper.Color32ArrayToFloatArray(pixels, 2, 3);

        // Apply normalization: (val - mean) / std
        float[] mean = logic.Mean;
        float[] std = logic.Std;
        for (int h = 0; h < 2; h++)
            for (int w = 0; w < 3; w++)
                for (int c = 0; c < 3; c++)
                    floatImg[h, w, c] = (floatImg[h, w, c] - mean[c]) / std[c];

        // Transpose to CHW
        float[,,] chw = Sam2TestHelper.TransposeHWCtoCHW(floatImg);

        // Python reference values (exact from generate_sam2_reference.py)
        float[,,] pythonCHW = new float[3, 2, 3]
        {
            // Channel 0 (R)
            {
                { -0.40542852f, -1.26166622f, 1.30704689f },
                { -1.94665639f, 2.24890830f, -2.11790393f }
            },
            // Channel 1 (G)
            {
                { 0.59033624f, -0.28501398f, -1.16036413f },
                { -1.68557422f, 0.20518221f, 2.42857143f }
            },
            // Channel 2 (B)
            {
                { 1.68139439f, 0.80993475f, -0.06152503f },
                { -1.28156863f, -0.68897597f, -1.80444444f }
            }
        };

        // Compare every element
        for (int c = 0; c < 3; c++)
            for (int h = 0; h < 2; h++)
                for (int w = 0; w < 3; w++)
                    Assert.That(chw[c, h, w], Is.EqualTo(pythonCHW[c, h, w]).Within(Tol),
                        $"CHW[{c},{h},{w}]: C#={chw[c, h, w]:F8} vs Python={pythonCHW[c, h, w]:F8}");
    }

    // -----------------------------------------------------------
    // 5. Coordinate scaling vs Python
    //    Python: coords * 1024 / size
    //    (500, 300) on 1000x600 -> (512.0, 512.0)
    //    (200, 100) on 1000x600 -> (204.8, 170.6667)
    // -----------------------------------------------------------
    [Test]
    public void Python_CoordinateScaling()
    {
        float[,] coords = new float[,] { { 500f, 300f }, { 200f, 100f } };

        float[,] scaled = logic.ApplyCoordinateScaling(coords, 600, 1000);

        Assert.That(scaled[0, 0], Is.EqualTo(512.0f).Within(Tol),
            "Point0 X: C# vs Python(512.0)");
        Assert.That(scaled[0, 1], Is.EqualTo(512.0f).Within(Tol),
            "Point0 Y: C# vs Python(512.0)");
        Assert.That(scaled[1, 0], Is.EqualTo(204.8f).Within(Tol),
            "Point1 X: C# vs Python(204.8)");
        Assert.That(scaled[1, 1], Is.EqualTo(170.66667f).Within(Tol),
            "Point1 Y: C# vs Python(170.6667)");
    }

    // -----------------------------------------------------------
    // 6. Bilinear resize 2x2->4x4 vs Python (align_corners=False)
    //    Python: F.interpolate(src, (4,4), mode='bilinear', align_corners=False)
    // -----------------------------------------------------------
    [Test]
    public void Python_BilinearResize_2x2To4x4()
    {
        float[,] src = new float[,] { { 0f, 1f }, { 2f, 3f } };

        float[,] dst = logic.ResizeBilinear(src, 4, 4);

        float[,] pythonRef = new float[,]
        {
            { 0.00000000f, 0.25000000f, 0.75000000f, 1.00000000f },
            { 0.50000000f, 0.75000000f, 1.25000000f, 1.50000000f },
            { 1.50000000f, 1.75000000f, 2.25000000f, 2.50000000f },
            { 2.00000000f, 2.25000000f, 2.75000000f, 3.00000000f },
        };

        for (int y = 0; y < 4; y++)
            for (int x = 0; x < 4; x++)
                Assert.That(dst[y, x], Is.EqualTo(pythonRef[y, x]).Within(Tol),
                    $"Bilinear[{y},{x}]: C#={dst[y, x]:F8} vs Python={pythonRef[y, x]:F8}");
    }

    // -----------------------------------------------------------
    // 7. Mask postprocess: resize 2x2->4x4 + threshold (align_corners=False)
    //    Python: F.interpolate(masks, (4,4), mode='bilinear', align_corners=False)
    //    Mask 0: 2/16 true, Mask 1: 16/16 true,
    //    Mask 2: 11/16 true, Mask 3: 0/16 true
    // -----------------------------------------------------------
    [Test]
    public void Python_MaskPostprocess_Resize()
    {
        float[,,,] rawMasks = new float[1, 4, 2, 2];
        rawMasks[0, 0, 0, 0] = -5f; rawMasks[0, 0, 0, 1] = -3f;
        rawMasks[0, 0, 1, 0] = -1f; rawMasks[0, 0, 1, 1] = 0.5f;
        rawMasks[0, 1, 0, 0] = 5f; rawMasks[0, 1, 0, 1] = 8f;
        rawMasks[0, 1, 1, 0] = 6f; rawMasks[0, 1, 1, 1] = 10f;
        rawMasks[0, 2, 0, 0] = -2f; rawMasks[0, 2, 0, 1] = 3f;
        rawMasks[0, 2, 1, 0] = 4f; rawMasks[0, 2, 1, 1] = -1f;
        rawMasks[0, 3, 0, 0] = -1f; rawMasks[0, 3, 0, 1] = -2f;
        rawMasks[0, 3, 1, 0] = -3f; rawMasks[0, 3, 1, 1] = -4f;

        float[,,,] resized = logic.PostprocessMasks(rawMasks, 4, 4);

        // Python reference (align_corners=False)
        float[,] pyMask0 = new float[,]
        {
            { -5.0000f, -4.5000f, -3.5000f, -3.0000f },
            { -4.0000f, -3.5312f, -2.5938f, -2.1250f },
            { -2.0000f, -1.5938f, -0.7812f, -0.3750f },
            { -1.0000f, -0.6250f,  0.1250f,  0.5000f },
        };
        float[,] pyMask1 = new float[,]
        {
            {  5.0000f,  5.7500f,  7.2500f,  8.0000f },
            {  5.2500f,  6.0625f,  7.6875f,  8.5000f },
            {  5.7500f,  6.6875f,  8.5625f,  9.5000f },
            {  6.0000f,  7.0000f,  9.0000f, 10.0000f },
        };
        float[,] pyMask2 = new float[,]
        {
            { -2.0000f, -0.7500f,  1.7500f,  3.0000f },
            { -0.5000f,  0.1250f,  1.3750f,  2.0000f },
            {  2.5000f,  1.8750f,  0.6250f,  0.0000f },
            {  4.0000f,  2.7500f,  0.2500f, -1.0000f },
        };
        float[,] pyMask3 = new float[,]
        {
            { -1.0000f, -1.2500f, -1.7500f, -2.0000f },
            { -1.5000f, -1.7500f, -2.2500f, -2.5000f },
            { -2.5000f, -2.7500f, -3.2500f, -3.5000f },
            { -3.0000f, -3.2500f, -3.7500f, -4.0000f },
        };

        float[][,] pyMasks = { pyMask0, pyMask1, pyMask2, pyMask3 };

        for (int c = 0; c < 4; c++)
            for (int y = 0; y < 4; y++)
                for (int x = 0; x < 4; x++)
                    Assert.That(resized[0, c, y, x],
                        Is.EqualTo(pyMasks[c][y, x]).Within(1e-3f),
                        $"Mask{c}[{y},{x}]: C#={resized[0, c, y, x]:F4} vs Python={pyMasks[c][y, x]:F4}");
    }

    [Test]
    public void Python_MaskPostprocess_BoolTrueCount()
    {
        float[,,,] rawMasks = new float[1, 4, 2, 2];
        rawMasks[0, 0, 0, 0] = -5f; rawMasks[0, 0, 0, 1] = -3f;
        rawMasks[0, 0, 1, 0] = -1f; rawMasks[0, 0, 1, 1] = 0.5f;
        rawMasks[0, 1, 0, 0] = 5f; rawMasks[0, 1, 0, 1] = 8f;
        rawMasks[0, 1, 1, 0] = 6f; rawMasks[0, 1, 1, 1] = 10f;
        rawMasks[0, 2, 0, 0] = -2f; rawMasks[0, 2, 0, 1] = 3f;
        rawMasks[0, 2, 1, 0] = 4f; rawMasks[0, 2, 1, 1] = -1f;
        rawMasks[0, 3, 0, 0] = -1f; rawMasks[0, 3, 0, 1] = -2f;
        rawMasks[0, 3, 1, 0] = -3f; rawMasks[0, 3, 1, 1] = -4f;

        float[,,,] resized = logic.PostprocessMasks(rawMasks, 4, 4);
        bool[][,] boolMasks = logic.ConvertToBoolMasks(resized, 0.0f);

        // Python (align_corners=False): [2, 16, 11, 0] true pixels per mask
        // Mask2[2,3]=0.0 exactly at boundary; float32 may vary by 1 pixel.
        int[] pythonTrueCount = { 2, 16, 11, 0 };
        int[] allowedDelta = { 0, 0, 1, 0 }; // tolerance for boundary pixels

        for (int c = 0; c < 4; c++)
        {
            int trueCount = 0;
            for (int y = 0; y < 4; y++)
                for (int x = 0; x < 4; x++)
                    if (boolMasks[c][y, x]) trueCount++;

            Assert.That(Math.Abs(trueCount - pythonTrueCount[c]), Is.LessThanOrEqualTo(allowedDelta[c]),
                $"Mask{c}: C# true count={trueCount} vs Python={pythonTrueCount[c]} (delta tolerance={allowedDelta[c]}, boundary float32 precision)");
        }

        // Verify boundary pixel: Mask2[2,3]=0.0 in Python (align_corners=False)
        Assert.That(Math.Abs(resized[0, 2, 2, 3]), Is.LessThan(1e-3f),
            $"Mask2[2,3] boundary value={resized[0, 2, 2, 3]:E6} should be ~0.0");
    }

    // -----------------------------------------------------------
    // 8. Backbone features: flatten(2).permute(2, 0, 1) vs Python
    //    Python: input (1,2,2,2) = [1..8]
    //    Output (4, 1, 2):
    //      [hw=0]: [[1, 5]], [hw=1]: [[2, 6]],
    //      [hw=2]: [[3, 7]], [hw=3]: [[4, 8]]
    // -----------------------------------------------------------
    [Test]
    public void Python_BackboneFeatures_FlattenPermute()
    {
        float[,,,] fpn = new float[1, 2, 2, 2];
        fpn[0, 0, 0, 0] = 1; fpn[0, 0, 0, 1] = 2;
        fpn[0, 0, 1, 0] = 3; fpn[0, 0, 1, 1] = 4;
        fpn[0, 1, 0, 0] = 5; fpn[0, 1, 0, 1] = 6;
        fpn[0, 1, 1, 0] = 7; fpn[0, 1, 1, 1] = 8;

        float[][,,,] fpnArray = new float[3][,,,] { fpn, fpn, fpn };
        float[][,,] result = logic.PrepareBackboneFeatures(fpnArray);

        // Python output[hw, n, c]
        float[,] pythonRef = new float[,]
        {
            // [hw=0]: n=0, c=0..1
            { 1f, 5f },
            // [hw=1]
            { 2f, 6f },
            // [hw=2]
            { 3f, 7f },
            // [hw=3]
            { 4f, 8f },
        };

        for (int hw = 0; hw < 4; hw++)
            for (int c = 0; c < 2; c++)
                Assert.That(result[0][hw, 0, c],
                    Is.EqualTo(pythonRef[hw, c]).Within(Tol),
                    $"backbone[{hw},0,{c}]: C#={result[0][hw, 0, c]} vs Python={pythonRef[hw, c]}");
    }

    // -----------------------------------------------------------
    // 9. Transpose (2,0,1) vs Python
    //    Python: np.arange(24).reshape(2,3,4).transpose(2,0,1)
    //    transposed[0,0,0]=0, [1,0,1]=5, [3,1,2]=23
    // -----------------------------------------------------------
    [Test]
    public void Python_Transpose201()
    {
        float[,,] input = new float[2, 3, 4];
        float val = 0;
        for (int i = 0; i < 2; i++)
            for (int j = 0; j < 3; j++)
                for (int k = 0; k < 4; k++)
                    input[i, j, k] = val++;

        float[,,] result = Sam2TestHelper.Transpose201(input);

        // Python reference
        Assert.That(result[0, 0, 0], Is.EqualTo(0f).Within(Tol), "[0,0,0]=0");
        Assert.That(result[1, 0, 1], Is.EqualTo(5f).Within(Tol), "[1,0,1]=5");
        Assert.That(result[3, 1, 2], Is.EqualTo(23f).Within(Tol), "[3,1,2]=23");
    }

    // -----------------------------------------------------------
    // 10. Vision Pos Embeds vs Python
    //     Python: input (1,2,3,3) = arange(18)
    //     output[7,0,1] = 16.0 (= input[0,1,2,1])
    // -----------------------------------------------------------
    [Test]
    public void Python_VisionPosEmbeds()
    {
        float[][,,,] inputs = new float[1][,,,];
        inputs[0] = new float[1, 2, 3, 3];
        float val = 0;
        for (int n = 0; n < 1; n++)
            for (int c = 0; c < 2; c++)
                for (int h = 0; h < 3; h++)
                    for (int w = 0; w < 3; w++)
                        inputs[0][n, c, h, w] = val++;

        float[][,,] result = Sam2TestHelper.ProcessVisionPosEmbeds(inputs);

        // Output shape: (9, 1, 2)
        Assert.That(result[0].GetLength(0), Is.EqualTo(9));
        Assert.That(result[0].GetLength(1), Is.EqualTo(1));
        Assert.That(result[0].GetLength(2), Is.EqualTo(2));

        // Python: output[7,0,1] = input[0,1,2,1] = 16.0
        Assert.That(result[0][7, 0, 1], Is.EqualTo(16f).Within(Tol),
            "output[7,0,1]=16 (Python reference)");
        Assert.That(result[0][7, 0, 1], Is.EqualTo(inputs[0][0, 1, 2, 1]).Within(Tol),
            "output[7,0,1] == input[0,1,2,1]");
    }

    // -----------------------------------------------------------
    // 11. Full mask pipeline comparison: preprocessing errors
    //     Compute max absolute error across all values
    // -----------------------------------------------------------
    [Test]
    public void Python_MaxAbsoluteError_Normalization()
    {
        // Test multiple pixel values and report max error
        byte[,] testPixels = new byte[,]
        {
            { 0, 0, 0 },
            { 255, 255, 255 },
            { 128, 64, 192 },
            { 100, 200, 50 },
            { 1, 127, 254 },
            { 10, 20, 30 },
            { 200, 150, 100 },
        };

        float[] mean = logic.Mean;
        float[] std = logic.Std;

        // Python uses float64 internally, but SAM2 model inputs are float32
        // We compare against float32-precision Python values
        double maxError = 0;

        for (int i = 0; i < testPixels.GetLength(0); i++)
        {
            byte r = testPixels[i, 0], g = testPixels[i, 1], b = testPixels[i, 2];
            Color32[] px = new Color32[] { new Color32(r, g, b, 255) };
            float[,,,] result = logic.PreprocessImage(px, 1, 1, 1);

            // Python equivalent (using double for reference)
            double pyR = (r / 255.0 - 0.485) / 0.229;
            double pyG = (g / 255.0 - 0.456) / 0.224;
            double pyB = (b / 255.0 - 0.406) / 0.225;

            double errR = Math.Abs(result[0, 0, 0, 0] - pyR);
            double errG = Math.Abs(result[0, 1, 0, 0] - pyG);
            double errB = Math.Abs(result[0, 2, 0, 0] - pyB);

            maxError = Math.Max(maxError, Math.Max(errR, Math.Max(errG, errB)));
        }

        Console.WriteLine($"Max absolute error (C# float32 vs Python float64): {maxError:E6}");

        // float32 precision: ~7 decimal digits, max error should be < 1e-5
        Assert.That(maxError, Is.LessThan(1e-4),
            $"Max normalization error between C# and Python should be < 1e-4, got {maxError:E6}");
    }

    [Test]
    public void Python_MaxAbsoluteError_BilinearResize()
    {
        // Compare bilinear resize with various source values
        float[,] src = new float[,]
        {
            { -5f, -3f },
            { -1f, 0.5f }
        };

        float[,] dst = logic.ResizeBilinear(src, 4, 4);

        // Python reference values (align_corners=False, Mask 0)
        float[,] pyRef = new float[,]
        {
            { -5.0000f, -4.5000f, -3.5000f, -3.0000f },
            { -4.0000f, -3.5312f, -2.5938f, -2.1250f },
            { -2.0000f, -1.5938f, -0.7812f, -0.3750f },
            { -1.0000f, -0.6250f,  0.1250f,  0.5000f },
        };

        double maxError = 0;
        for (int y = 0; y < 4; y++)
            for (int x = 0; x < 4; x++)
            {
                double err = Math.Abs(dst[y, x] - pyRef[y, x]);
                maxError = Math.Max(maxError, err);
            }

        Console.WriteLine($"Max bilinear resize error: {maxError:E6}");
        Assert.That(maxError, Is.LessThan(1e-3),
            $"Max bilinear resize error should be < 1e-3, got {maxError:E6}");
    }

    // -----------------------------------------------------------
    // 12. Mask 2 detailed comparison (partial mask, align_corners=False)
    //     Python: 11/16 true pixels with specific pattern
    // -----------------------------------------------------------
    [Test]
    public void Python_Mask2_DetailedBoolPattern()
    {
        float[,,,] rawMasks = new float[1, 1, 2, 2];
        rawMasks[0, 0, 0, 0] = -2f;
        rawMasks[0, 0, 0, 1] = 3f;
        rawMasks[0, 0, 1, 0] = 4f;
        rawMasks[0, 0, 1, 1] = -1f;

        float[,,,] resized = logic.PostprocessMasks(rawMasks, 4, 4);
        bool[][,] boolMasks = logic.ConvertToBoolMasks(resized, 0.0f);

        // Python bool mask pattern (align_corners=False):
        // [False, False, True,  True ]
        // [False, True,  True,  True ]
        // [True,  True,  True,  False]
        // [True,  True,  True,  False]

        // Clearly positive values -> True
        Assert.That(boolMasks[0][0, 2], Is.True, "[0,2]: clearly positive");
        Assert.That(boolMasks[0][0, 3], Is.True, "[0,3]: clearly positive");
        Assert.That(boolMasks[0][1, 1], Is.True, "[1,1]: clearly positive");
        Assert.That(boolMasks[0][1, 2], Is.True, "[1,2]: clearly positive");
        Assert.That(boolMasks[0][1, 3], Is.True, "[1,3]: clearly positive");
        Assert.That(boolMasks[0][2, 0], Is.True, "[2,0]: clearly positive");
        Assert.That(boolMasks[0][2, 1], Is.True, "[2,1]: clearly positive");
        Assert.That(boolMasks[0][2, 2], Is.True, "[2,2]: clearly positive");
        Assert.That(boolMasks[0][3, 0], Is.True, "[3,0]: clearly positive");
        Assert.That(boolMasks[0][3, 1], Is.True, "[3,1]: clearly positive");
        Assert.That(boolMasks[0][3, 2], Is.True, "[3,2]: clearly positive");

        // Clearly negative values -> False
        Assert.That(boolMasks[0][0, 0], Is.False, "[0,0]: clearly negative");
        Assert.That(boolMasks[0][0, 1], Is.False, "[0,1]: clearly negative");
        Assert.That(boolMasks[0][1, 0], Is.False, "[1,0]: clearly negative");
        Assert.That(boolMasks[0][3, 3], Is.False, "[3,3]: clearly negative");

        // Boundary value [2,3]: Python = 0.0000 (align_corners=False)
        Assert.That(Math.Abs(resized[0, 0, 2, 3]), Is.LessThan(1e-3f),
            $"Mask2[2,3] boundary value={resized[0, 0, 2, 3]:E6} should be ~0.0");
    }

    // -----------------------------------------------------------
    // 13. Error summary: full pipeline (preprocess + postprocess)
    // -----------------------------------------------------------
    [Test]
    public void Python_ErrorSummary_FullPipeline()
    {
        // Test the complete preprocessing pipeline on a known image
        // and verify cumulative errors remain within acceptable bounds

        // Create a 4x4 test image with diverse pixel values
        Color32[] testImg = new Color32[16];
        for (int i = 0; i < 16; i++)
        {
            byte r = (byte)(i * 17);       // 0, 17, 34, ..., 255
            byte g = (byte)(255 - i * 17); // 255, 238, 221, ..., 0
            byte b = (byte)(i * 8 + 64);   // 64, 72, 80, ..., 184
            testImg[i] = new Color32(r, g, b, 255);
        }

        // Preprocess with imageSize=4 (no resize needed)
        float[,,,] result = logic.PreprocessImage(testImg, 4, 4, 4);

        // Verify shape
        Assert.That(result.GetLength(0), Is.EqualTo(1), "N=1");
        Assert.That(result.GetLength(1), Is.EqualTo(3), "C=3");
        Assert.That(result.GetLength(2), Is.EqualTo(4), "H=4");
        Assert.That(result.GetLength(3), Is.EqualTo(4), "W=4");

        // Compute expected values using Python formula and measure errors
        float[] mean = logic.Mean;
        float[] std = logic.Std;
        double maxError = 0;
        int totalValues = 0;
        double sumError = 0;

        for (int h = 0; h < 4; h++)
        {
            for (int w = 0; w < 4; w++)
            {
                int idx = h * 4 + w;
                double pyR = (testImg[idx].r / 255.0 - mean[0]) / std[0];
                double pyG = (testImg[idx].g / 255.0 - mean[1]) / std[1];
                double pyB = (testImg[idx].b / 255.0 - mean[2]) / std[2];

                double errR = Math.Abs(result[0, 0, h, w] - pyR);
                double errG = Math.Abs(result[0, 1, h, w] - pyG);
                double errB = Math.Abs(result[0, 2, h, w] - pyB);

                maxError = Math.Max(maxError, Math.Max(errR, Math.Max(errG, errB)));
                sumError += errR + errG + errB;
                totalValues += 3;
            }
        }

        double avgError = sumError / totalValues;
        Console.WriteLine($"Full pipeline error summary:");
        Console.WriteLine($"  Max absolute error: {maxError:E6}");
        Console.WriteLine($"  Average absolute error: {avgError:E6}");
        Console.WriteLine($"  Total values compared: {totalValues}");

        Assert.That(maxError, Is.LessThan(1e-4),
            $"Max pipeline error should be < 1e-4, got {maxError:E6}");
        Assert.That(avgError, Is.LessThan(1e-5),
            $"Average pipeline error should be < 1e-5, got {avgError:E6}");
    }
}
