/* MediaPipe Pose World Landmarks Python Reference Comparison Tests */
/* Copyright 2025 AXELL CORPORATION and ax Inc. */
/*
 * These tests compare C# MediaPipe Pose World Landmarks processing output
 * against exact numerical values computed by the Python reference implementation.
 *
 * Ground truth generated by: generate_mediapipe_reference.py
 *
 * Processing steps validated:
 *   1. Sigmoid activation: 1 / (1 + exp(-x))
 *   2. Pixel normalization: value / 255.0
 *   3. Box decoding: raw SSD outputs + anchors -> bounding boxes
 *   4. Landmark decoding: 195-value buffer -> 33 landmarks (x, y, z, vis, pres)
 *   5. Affine inverse coordinate transform
 *   6. Derived keypoints (shoulder center, body center)
 *
 * Python source:
 *   - mediapipe pose estimation pipeline
 *   - SSD anchor-based detection decoding
 *   - Landmark coordinate normalization (value / 256.0)
 *   - Sigmoid confidence: sigmoid(min(visibility, presence))
 */

using NUnit.Framework;
using System;
using System.Collections.Generic;

[TestFixture]
public class PythonComparisonTest
{
    private MediapipePoseWorldProcessor processor = null!;

    // Tolerance for float comparison between Python and C#
    // Python uses float64 by default; C# uses float32.
    // 1e-4 accounts for float32 precision difference.
    private const float Tol = 1e-4f;

    [SetUp]
    public void SetUp()
    {
        processor = new MediapipePoseWorldProcessor();
    }

    // =======================================================
    // Python ground truth values (from generate_mediapipe_reference.py)
    // =======================================================

    // -----------------------------------------------------------
    // 1. Sigmoid activation vs Python
    //    Python: 1.0 / (1.0 + np.exp(-x))
    // -----------------------------------------------------------
    [Test]
    public void Python_Sigmoid_ZeroInput()
    {
        Assert.That(processor.Sigmoid(0.0f), Is.EqualTo(0.5f).Within(Tol),
            "sigmoid(0) = 0.5");
    }

    [Test]
    public void Python_Sigmoid_PositiveInputs()
    {
        Assert.That(processor.Sigmoid(1.0f), Is.EqualTo(0.7310585786f).Within(Tol),
            "sigmoid(1.0)");
        Assert.That(processor.Sigmoid(5.0f), Is.EqualTo(0.9933071491f).Within(Tol),
            "sigmoid(5.0)");
        Assert.That(processor.Sigmoid(0.5f), Is.EqualTo(0.6224593312f).Within(Tol),
            "sigmoid(0.5)");
        Assert.That(processor.Sigmoid(2.3f), Is.EqualTo(0.9088770390f).Within(Tol),
            "sigmoid(2.3)");
    }

    [Test]
    public void Python_Sigmoid_NegativeInputs()
    {
        Assert.That(processor.Sigmoid(-1.0f), Is.EqualTo(0.2689414214f).Within(Tol),
            "sigmoid(-1.0)");
        Assert.That(processor.Sigmoid(-5.0f), Is.EqualTo(0.0066928509f).Within(Tol),
            "sigmoid(-5.0)");
        Assert.That(processor.Sigmoid(-0.5f), Is.EqualTo(0.3775406688f).Within(Tol),
            "sigmoid(-0.5)");
        Assert.That(processor.Sigmoid(-2.3f), Is.EqualTo(0.0911229610f).Within(Tol),
            "sigmoid(-2.3)");
    }

    [Test]
    public void Python_Sigmoid_ExtremeInputs()
    {
        // Python: sigmoid(100) = 1.0, sigmoid(-100) = 0.0
        Assert.That(processor.Sigmoid(100.0f), Is.EqualTo(1.0f).Within(Tol),
            "sigmoid(100) ≈ 1.0");
        Assert.That(processor.Sigmoid(-100.0f), Is.EqualTo(0.0f).Within(Tol),
            "sigmoid(-100) ≈ 0.0");
    }

    [Test]
    public void Python_Sigmoid_Symmetry()
    {
        // Python: sigmoid(x) + sigmoid(-x) = 1.0
        float[] testValues = { 0.5f, 1.0f, 2.3f, 5.0f };
        foreach (float v in testValues)
        {
            float sum = processor.Sigmoid(v) + processor.Sigmoid(-v);
            Assert.That(sum, Is.EqualTo(1.0f).Within(Tol),
                $"sigmoid({v}) + sigmoid(-{v}) = 1.0");
        }
    }

    // -----------------------------------------------------------
    // 2. Pixel normalization vs Python
    //    Python: pixel_value / 255.0
    // -----------------------------------------------------------
    [Test]
    public void Python_PixelNormalization()
    {
        Assert.That(processor.NormalizePixel(0), Is.EqualTo(0.0f).Within(Tol),
            "0 / 255");
        Assert.That(processor.NormalizePixel(1), Is.EqualTo(0.0039215686f).Within(Tol),
            "1 / 255");
        Assert.That(processor.NormalizePixel(127), Is.EqualTo(0.4980392157f).Within(Tol),
            "127 / 255");
        Assert.That(processor.NormalizePixel(128), Is.EqualTo(0.5019607843f).Within(Tol),
            "128 / 255");
        Assert.That(processor.NormalizePixel(254), Is.EqualTo(0.9960784314f).Within(Tol),
            "254 / 255");
        Assert.That(processor.NormalizePixel(255), Is.EqualTo(1.0f).Within(Tol),
            "255 / 255");
    }

    [Test]
    public void Python_PreprocessToFloat_MatchesPythonDivide255()
    {
        byte[] pixels = new byte[] {
            128, 64, 192,  // pixel 0
            0, 255, 127    // pixel 1
        };

        float[] result = processor.PreprocessToFloat(pixels, 2, 1);

        Assert.That(result[0], Is.EqualTo(128f / 255f).Within(Tol), "R0");
        Assert.That(result[1], Is.EqualTo(64f / 255f).Within(Tol), "G0");
        Assert.That(result[2], Is.EqualTo(192f / 255f).Within(Tol), "B0");
        Assert.That(result[3], Is.EqualTo(0f / 255f).Within(Tol), "R1");
        Assert.That(result[4], Is.EqualTo(255f / 255f).Within(Tol), "G1");
        Assert.That(result[5], Is.EqualTo(127f / 255f).Within(Tol), "B1");
    }

    // -----------------------------------------------------------
    // 3. Box decoding vs Python
    //    Python: SSD anchor-based decoding
    //    Anchors: [[0.5,0.5,1,1], [0.25,0.25,0.5,0.5], [0.75,0.75,0.5,0.5]]
    //    Raw scores: [2.0, 3.0, -1.0]
    // -----------------------------------------------------------
    [Test]
    public void Python_BoxDecoding_ScoreFiltering()
    {
        // 3 tensors, scores [2.0, 3.0, -1.0]
        // sigmoid(-1.0) = 0.2689 < 0.5 -> tensor 2 filtered out
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.25f, 0.25f, 0.5f, 0.5f },
            { 0.75f, 0.75f, 0.5f, 0.5f }
        };

        float[] rawBoxes = new float[]
        {
            10f, 20f, 50f, 60f,  15f, 25f, 30f, 35f, 40f, 45f, 50f, 55f,
            5f,  10f, 30f, 40f,  8f,  12f, 16f, 20f, 24f, 28f, 32f, 36f,
            8f,  15f, 45f, 55f,  12f, 18f, 22f, 28f, 35f, 40f, 42f, 48f,
        };
        float[] rawScores = new float[] { 2.0f, 3.0f, -1.0f };

        List<TestBox> boxes = processor.DecodeBoxes(rawBoxes, rawScores, anchors, 3);

        // Tensor 2 (score -1.0) should be filtered
        Assert.That(boxes.Count, Is.EqualTo(2), "2 boxes survive score filter");
    }

    [Test]
    public void Python_BoxDecoding_Tensor0_Coordinates()
    {
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.25f, 0.25f, 0.5f, 0.5f },
            { 0.75f, 0.75f, 0.5f, 0.5f }
        };

        float[] rawBoxes = new float[]
        {
            10f, 20f, 50f, 60f,  15f, 25f, 30f, 35f, 40f, 45f, 50f, 55f,
            5f,  10f, 30f, 40f,  8f,  12f, 16f, 20f, 24f, 28f, 32f, 36f,
            8f,  15f, 45f, 55f,  12f, 18f, 22f, 28f, 35f, 40f, 42f, 48f,
        };
        float[] rawScores = new float[] { 2.0f, 3.0f, -1.0f };

        List<TestBox> boxes = processor.DecodeBoxes(rawBoxes, rawScores, anchors, 3);

        // Find box from tensor 0 (score ~0.881) - boxes are sorted by score desc,
        // so tensor 1 (score ~0.953) comes first
        // Tensor 1 Python reference:
        //   xMin=0.2276785714, yMin=0.2276785714, xMax=0.2946428571, yMax=0.3169642857
        TestBox box1 = boxes[0]; // highest score = tensor 1
        Assert.That(box1.xMin, Is.EqualTo(0.2276785714f).Within(Tol), "T1 xMin");
        Assert.That(box1.yMin, Is.EqualTo(0.2276785714f).Within(Tol), "T1 yMin");
        Assert.That(box1.xMax, Is.EqualTo(0.2946428571f).Within(Tol), "T1 xMax");
        Assert.That(box1.yMax, Is.EqualTo(0.3169642857f).Within(Tol), "T1 yMax");

        // Tensor 0 Python reference:
        //   xMin=0.4330357143, yMin=0.4553571429, xMax=0.6562500000, yMax=0.7232142857
        TestBox box0 = boxes[1]; // second highest score = tensor 0
        Assert.That(box0.xMin, Is.EqualTo(0.4330357143f).Within(Tol), "T0 xMin");
        Assert.That(box0.yMin, Is.EqualTo(0.4553571429f).Within(Tol), "T0 yMin");
        Assert.That(box0.xMax, Is.EqualTo(0.6562500000f).Within(Tol), "T0 xMax");
        Assert.That(box0.yMax, Is.EqualTo(0.7232142857f).Within(Tol), "T0 yMax");
    }

    [Test]
    public void Python_BoxDecoding_Keypoints()
    {
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.25f, 0.25f, 0.5f, 0.5f },
            { 0.75f, 0.75f, 0.5f, 0.5f }
        };

        float[] rawBoxes = new float[]
        {
            10f, 20f, 50f, 60f,  15f, 25f, 30f, 35f, 40f, 45f, 50f, 55f,
            5f,  10f, 30f, 40f,  8f,  12f, 16f, 20f, 24f, 28f, 32f, 36f,
            8f,  15f, 45f, 55f,  12f, 18f, 22f, 28f, 35f, 40f, 42f, 48f,
        };
        float[] rawScores = new float[] { 2.0f, 3.0f, -1.0f };

        List<TestBox> boxes = processor.DecodeBoxes(rawBoxes, rawScores, anchors, 3);

        // Tensor 1 (index 0 in sorted result) keypoints
        // Python: kp0=(0.2678571429, 0.2767857143)
        TestBox box = boxes[0];
        Assert.That(box.keypoints[0][0], Is.EqualTo(0.2678571429f).Within(Tol), "T1 kp0.x");
        Assert.That(box.keypoints[0][1], Is.EqualTo(0.2767857143f).Within(Tol), "T1 kp0.y");

        // kp3=(0.3214285714, 0.3303571429)
        Assert.That(box.keypoints[3][0], Is.EqualTo(0.3214285714f).Within(Tol), "T1 kp3.x");
        Assert.That(box.keypoints[3][1], Is.EqualTo(0.3303571429f).Within(Tol), "T1 kp3.y");
    }

    // -----------------------------------------------------------
    // 4. Landmark decoding vs Python
    //    Python: x = raw[i*5] / 256, y = raw[i*5+1] / 256, z = raw[i*5+2] / 256
    //            conf = sigmoid(min(visibility, presence))
    // -----------------------------------------------------------
    [Test]
    public void Python_LandmarkDecoding_Nose()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        // Python: Landmark 0 (Nose): x=0.5, y=0.2, z=-0.9, conf=0.9241418200
        Assert.That(landmarks[0].x, Is.EqualTo(0.5000000000f).Within(Tol), "Nose x");
        Assert.That(landmarks[0].y, Is.EqualTo(0.2000000000f).Within(Tol), "Nose y");
        Assert.That(landmarks[0].z, Is.EqualTo(-0.9000000000f).Within(Tol), "Nose z");
        Assert.That(landmarks[0].confidence, Is.EqualTo(0.9241418200f).Within(Tol), "Nose conf");
    }

    [Test]
    public void Python_LandmarkDecoding_LeftEye()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        // Python: Landmark 2 (LeftEye): x=0.4492187500, y=0.1718750000, z=-0.8789062500, conf=0.8807970780
        Assert.That(landmarks[2].x, Is.EqualTo(0.4492187500f).Within(Tol), "LeftEye x");
        Assert.That(landmarks[2].y, Is.EqualTo(0.1718750000f).Within(Tol), "LeftEye y");
        Assert.That(landmarks[2].z, Is.EqualTo(-0.8789062500f).Within(Tol), "LeftEye z");
        Assert.That(landmarks[2].confidence, Is.EqualTo(0.8807970780f).Within(Tol), "LeftEye conf");
    }

    [Test]
    public void Python_LandmarkDecoding_Shoulders()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        // Python: Landmark 11 (LeftShoulder): x=0.3125, y=0.46875, z=-0.390625, conf=0.8581489351
        Assert.That(landmarks[11].x, Is.EqualTo(0.3125000000f).Within(Tol), "LShoulder x");
        Assert.That(landmarks[11].y, Is.EqualTo(0.4687500000f).Within(Tol), "LShoulder y");
        Assert.That(landmarks[11].z, Is.EqualTo(-0.3906250000f).Within(Tol), "LShoulder z");
        Assert.That(landmarks[11].confidence, Is.EqualTo(0.8581489351f).Within(Tol), "LShoulder conf");

        // Python: Landmark 12 (RightShoulder): x=0.6875, y=0.4609375, z=-0.3710937500, conf=0.8698915256
        Assert.That(landmarks[12].x, Is.EqualTo(0.6875000000f).Within(Tol), "RShoulder x");
        Assert.That(landmarks[12].y, Is.EqualTo(0.4609375000f).Within(Tol), "RShoulder y");
        Assert.That(landmarks[12].z, Is.EqualTo(-0.3710937500f).Within(Tol), "RShoulder z");
        Assert.That(landmarks[12].confidence, Is.EqualTo(0.8698915256f).Within(Tol), "RShoulder conf");
    }

    [Test]
    public void Python_LandmarkDecoding_Hips()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        // Python: Landmark 23 (LeftHip): x=0.390625, y=0.78125, z=-0.3125, conf=0.7858349830
        Assert.That(landmarks[23].x, Is.EqualTo(0.3906250000f).Within(Tol), "LHip x");
        Assert.That(landmarks[23].y, Is.EqualTo(0.7812500000f).Within(Tol), "LHip y");
        Assert.That(landmarks[23].z, Is.EqualTo(-0.3125000000f).Within(Tol), "LHip z");
        Assert.That(landmarks[23].confidence, Is.EqualTo(0.7858349830f).Within(Tol), "LHip conf");

        // Python: Landmark 24 (RightHip): x=0.609375, y=0.7734375, z=-0.3046875, conf=0.8021838886
        Assert.That(landmarks[24].x, Is.EqualTo(0.6093750000f).Within(Tol), "RHip x");
        Assert.That(landmarks[24].y, Is.EqualTo(0.7734375000f).Within(Tol), "RHip y");
        Assert.That(landmarks[24].z, Is.EqualTo(-0.3046875000f).Within(Tol), "RHip z");
        Assert.That(landmarks[24].confidence, Is.EqualTo(0.8021838886f).Within(Tol), "RHip conf");
    }

    [Test]
    public void Python_LandmarkDecoding_Count()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        Assert.That(landmarks.Length, Is.EqualTo(33), "33 landmarks");
    }

    // -----------------------------------------------------------
    // 5. Affine inverse coordinate transform vs Python
    //    Python: kp1=(0.5,0.4), kp2=(0.5,0.6), dscale=1.1
    //            scale=0.44, angle=-pi
    // -----------------------------------------------------------
    [Test]
    public void Python_AffineParams()
    {
        var (scale, angle) = processor.ComputeAffineParams(0.5f, 0.4f, 0.5f, 0.6f, 1.1f);

        Assert.That(scale, Is.EqualTo(0.4400000000f).Within(Tol), "scale");
        Assert.That(angle, Is.EqualTo(-3.1415926536f).Within(Tol), "angle");
    }

    [Test]
    public void Python_AffineInverse_CenterPoint()
    {
        // Python: landmark(0.5, 0.5) -> image(0.5, 0.4)
        var (x, y) = processor.ApplyAffineInverse(0.5f, 0.5f, 0.5f, 0.4f, 0.44f, -(float)Math.PI);

        Assert.That(x, Is.EqualTo(0.5000000000f).Within(Tol), "center x");
        Assert.That(y, Is.EqualTo(0.4000000000f).Within(Tol), "center y");
    }

    [Test]
    public void Python_AffineInverse_TopLeft()
    {
        // Python: landmark(0.0, 0.0) -> image(0.72, 0.62)
        var (x, y) = processor.ApplyAffineInverse(0.0f, 0.0f, 0.5f, 0.4f, 0.44f, -(float)Math.PI);

        Assert.That(x, Is.EqualTo(0.7200000000f).Within(Tol), "top-left x");
        Assert.That(y, Is.EqualTo(0.6200000000f).Within(Tol), "top-left y");
    }

    [Test]
    public void Python_AffineInverse_BottomRight()
    {
        // Python: landmark(1.0, 1.0) -> image(0.28, 0.18)
        var (x, y) = processor.ApplyAffineInverse(1.0f, 1.0f, 0.5f, 0.4f, 0.44f, -(float)Math.PI);

        Assert.That(x, Is.EqualTo(0.2800000000f).Within(Tol), "bottom-right x");
        Assert.That(y, Is.EqualTo(0.1800000000f).Within(Tol), "bottom-right y");
    }

    [Test]
    public void Python_AffineInverse_ArbitraryPoint()
    {
        // Python: landmark(0.25, 0.75) -> image(0.61, 0.29)
        var (x, y) = processor.ApplyAffineInverse(0.25f, 0.75f, 0.5f, 0.4f, 0.44f, -(float)Math.PI);

        Assert.That(x, Is.EqualTo(0.6100000000f).Within(Tol), "arbitrary x");
        Assert.That(y, Is.EqualTo(0.2900000000f).Within(Tol), "arbitrary y");
    }

    // -----------------------------------------------------------
    // 6. Derived keypoints vs Python
    // -----------------------------------------------------------
    [Test]
    public void Python_ShoulderCenter()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        var (x, y, z, conf) = processor.ComputeShoulderCenter(landmarks[11], landmarks[12]);

        // Python: x=0.5, y=0.4648437500, z=-0.3808593750, conf=0.8581489351
        Assert.That(x, Is.EqualTo(0.5000000000f).Within(Tol), "SC x");
        Assert.That(y, Is.EqualTo(0.4648437500f).Within(Tol), "SC y");
        Assert.That(z, Is.EqualTo(-0.3808593750f).Within(Tol), "SC z");
        Assert.That(conf, Is.EqualTo(0.8581489351f).Within(Tol), "SC conf");
    }

    [Test]
    public void Python_BodyCenter()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        var (x, y, z, conf) = processor.ComputeBodyCenter(
            landmarks[11], landmarks[12], landmarks[23], landmarks[24]);

        // Python: x=0.5, y=0.6210937500, z=-0.3447265625, conf=0.7858349830
        Assert.That(x, Is.EqualTo(0.5000000000f).Within(Tol), "BC x");
        Assert.That(y, Is.EqualTo(0.6210937500f).Within(Tol), "BC y");
        Assert.That(z, Is.EqualTo(-0.3447265625f).Within(Tol), "BC z");
        Assert.That(conf, Is.EqualTo(0.7858349830f).Within(Tol), "BC conf");
    }

    // -----------------------------------------------------------
    // 7. Max absolute error analysis (full pipeline)
    // -----------------------------------------------------------
    [Test]
    public void Python_MaxAbsoluteError_Sigmoid()
    {
        // Test multiple sigmoid values and report max error
        float[] testInputs = { 0f, 0.1f, 0.5f, 1f, 2f, 3f, 5f, -0.1f, -0.5f, -1f, -2f, -3f, -5f };
        double maxError = 0;

        foreach (float x in testInputs)
        {
            float csResult = processor.Sigmoid(x);
            double pyResult = 1.0 / (1.0 + Math.Exp(-x));
            double error = Math.Abs(csResult - pyResult);
            maxError = Math.Max(maxError, error);
        }

        Console.WriteLine($"Max sigmoid error (C# float32 vs Python float64): {maxError:E6}");
        Assert.That(maxError, Is.LessThan(1e-6),
            $"Max sigmoid error should be < 1e-6, got {maxError:E6}");
    }

    [Test]
    public void Python_MaxAbsoluteError_LandmarkDecoding()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        double maxError = 0;
        int totalValues = 0;

        for (int i = 0; i < 33; i++)
        {
            double pyX = rawOutput[i * 5] / 256.0;
            double pyY = rawOutput[i * 5 + 1] / 256.0;
            double pyZ = rawOutput[i * 5 + 2] / 256.0;
            double pyVis = rawOutput[i * 5 + 3];
            double pyPres = rawOutput[i * 5 + 4];
            double pyConf = 1.0 / (1.0 + Math.Exp(-Math.Min(pyVis, pyPres)));

            maxError = Math.Max(maxError, Math.Abs(landmarks[i].x - pyX));
            maxError = Math.Max(maxError, Math.Abs(landmarks[i].y - pyY));
            maxError = Math.Max(maxError, Math.Abs(landmarks[i].z - pyZ));
            maxError = Math.Max(maxError, Math.Abs(landmarks[i].confidence - pyConf));
            totalValues += 4;
        }

        Console.WriteLine($"Max landmark decoding error: {maxError:E6}");
        Console.WriteLine($"Total values compared: {totalValues}");

        Assert.That(maxError, Is.LessThan(1e-4),
            $"Max landmark error should be < 1e-4, got {maxError:E6}");
    }

    [Test]
    public void Python_MaxAbsoluteError_AffineTransform()
    {
        // Test multiple affine transforms and report max error
        float[,] testLandmarks = new float[,]
        {
            { 0.0f, 0.0f }, { 0.5f, 0.5f }, { 1.0f, 1.0f },
            { 0.25f, 0.75f }, { 0.75f, 0.25f }, { 0.1f, 0.9f }
        };

        float[] kp1xs = { 0.5f, 0.3f, 0.7f };
        float[] kp1ys = { 0.4f, 0.5f, 0.2f };
        float[] kp2xs = { 0.5f, 0.3f, 0.7f };
        float[] kp2ys = { 0.6f, 0.7f, 0.5f };

        double maxError = 0;

        for (int k = 0; k < kp1xs.Length; k++)
        {
            var (scale, angle) = processor.ComputeAffineParams(kp1xs[k], kp1ys[k], kp2xs[k], kp2ys[k]);

            double pyScale = 1.1 * Math.Sqrt(
                Math.Pow(kp1xs[k] - kp2xs[k], 2) + Math.Pow(kp1ys[k] - kp2ys[k], 2)) * 2;
            double pyAngle = Math.Atan2(kp1ys[k] - kp2ys[k], kp1xs[k] - kp2xs[k]) - Math.PI / 2;

            maxError = Math.Max(maxError, Math.Abs(scale - pyScale));
            maxError = Math.Max(maxError, Math.Abs(angle - pyAngle));

            for (int i = 0; i < testLandmarks.GetLength(0); i++)
            {
                var (csX, csY) = processor.ApplyAffineInverse(
                    testLandmarks[i, 0], testLandmarks[i, 1],
                    kp1xs[k], kp1ys[k], scale, angle);

                double cs = Math.Cos(-pyAngle);
                double ss = Math.Sin(-pyAngle);
                double lx = testLandmarks[i, 0] - 0.5;
                double ly = testLandmarks[i, 1] - 0.5;
                double pyX = (lx * cs + ly * ss) * pyScale + kp1xs[k];
                double pyY = (lx * -ss + ly * cs) * pyScale + kp1ys[k];

                maxError = Math.Max(maxError, Math.Abs(csX - pyX));
                maxError = Math.Max(maxError, Math.Abs(csY - pyY));
            }
        }

        Console.WriteLine($"Max affine transform error: {maxError:E6}");
        Assert.That(maxError, Is.LessThan(1e-4),
            $"Max affine error should be < 1e-4, got {maxError:E6}");
    }

    // -----------------------------------------------------------
    // 8. Full pipeline: landmark decode + derived keypoints
    // -----------------------------------------------------------
    [Test]
    public void Python_FullPipeline_LandmarkToDerivedKeypoints()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        // Verify full pipeline: raw -> decode -> derived keypoints
        var (scX, scY, scZ, scConf) = processor.ComputeShoulderCenter(landmarks[11], landmarks[12]);
        var (bcX, bcY, bcZ, bcConf) = processor.ComputeBodyCenter(
            landmarks[11], landmarks[12], landmarks[23], landmarks[24]);

        // Body center should be between shoulder center and hip center
        float hipCenterY = (landmarks[23].y + landmarks[24].y) / 2;
        Assert.That(bcY, Is.GreaterThan(scY), "BC.y > SC.y (body center below shoulders)");
        Assert.That(bcY, Is.LessThan(hipCenterY), "BC.y < hipCenter.y (body center above hips)");

        // Shoulder center X should be between left and right shoulders
        Assert.That(scX, Is.GreaterThan(landmarks[11].x), "SC.x > LShoulder.x");
        Assert.That(scX, Is.LessThan(landmarks[12].x), "SC.x < RShoulder.x");

        // Body center confidence should be min of all 4 joints
        float expectedConf = Math.Min(
            Math.Min(landmarks[11].confidence, landmarks[12].confidence),
            Math.Min(landmarks[23].confidence, landmarks[24].confidence));
        Assert.That(bcConf, Is.EqualTo(expectedConf).Within(Tol), "BC conf = min of 4 joints");
    }

    [Test]
    public void Python_FullPipeline_AffineWithDecodedLandmarks()
    {
        float[] rawOutput = CreateTestRawOutput();
        TestLandmark[] landmarks = processor.DecodeLandmarks(rawOutput);

        // Simulate affine transform on decoded nose landmark
        float affineXc = 0.5f, affineYc = 0.4f;
        float affineScale = 0.44f, affineAngle = -(float)Math.PI;

        var (imgX, imgY) = processor.ApplyAffineInverse(
            landmarks[0].x, landmarks[0].y,
            affineXc, affineYc, affineScale, affineAngle);

        // Verify the transform is reversible (center maps to center)
        var (centerX, centerY) = processor.ApplyAffineInverse(
            0.5f, 0.5f, affineXc, affineYc, affineScale, affineAngle);
        Assert.That(centerX, Is.EqualTo(affineXc).Within(Tol), "Center maps to affineXc");
        Assert.That(centerY, Is.EqualTo(affineYc).Within(Tol), "Center maps to affineYc");

        // The nose landmark image coordinate should be valid (within reasonable range)
        Assert.That(imgX, Is.GreaterThan(-1.0f).And.LessThan(2.0f), "Nose img.x in valid range");
        Assert.That(imgY, Is.GreaterThan(-1.0f).And.LessThan(2.0f), "Nose img.y in valid range");
    }

    // -----------------------------------------------------------
    // 9. NMS (Non-Maximum Suppression) vs Python
    // -----------------------------------------------------------
    [Test]
    public void Python_NMS_OverlappingBoxes()
    {
        // Create two overlapping boxes with same anchor
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.5f, 0.5f, 1.0f, 1.0f },
        };

        // Both produce nearly identical boxes -> should be merged
        float[] rawBoxes = new float[]
        {
            10f, 10f, 50f, 50f,  15f, 15f, 20f, 20f, 25f, 25f, 30f, 30f,
            11f, 11f, 50f, 50f,  15f, 15f, 20f, 20f, 25f, 25f, 30f, 30f,
        };
        float[] rawScores = new float[] { 2.0f, 1.5f };

        List<TestBox> boxes = processor.DecodeBoxes(rawBoxes, rawScores, anchors, 2);

        // After NMS, overlapping boxes should be merged into 1
        Assert.That(boxes.Count, Is.EqualTo(1), "Overlapping boxes merged");
    }

    [Test]
    public void Python_NMS_NonOverlappingBoxes()
    {
        // Create two non-overlapping boxes
        float[,] anchors = new float[,]
        {
            { 0.2f, 0.2f, 0.3f, 0.3f },
            { 0.8f, 0.8f, 0.3f, 0.3f },
        };

        float[] rawBoxes = new float[]
        {
            5f, 5f, 20f, 20f,  8f, 8f, 10f, 10f, 12f, 12f, 15f, 15f,
            5f, 5f, 20f, 20f,  8f, 8f, 10f, 10f, 12f, 12f, 15f, 15f,
        };
        float[] rawScores = new float[] { 2.0f, 2.0f };

        List<TestBox> boxes = processor.DecodeBoxes(rawBoxes, rawScores, anchors, 2);

        // Non-overlapping boxes should remain separate
        Assert.That(boxes.Count, Is.EqualTo(2), "Non-overlapping boxes preserved");
    }

    // -----------------------------------------------------------
    // Helper: Create test raw output matching generate_mediapipe_reference.py
    // -----------------------------------------------------------
    private float[] CreateTestRawOutput()
    {
        float[] rawOutput = new float[195];

        // Landmark 0 (Nose): x=128, y=51.2, z=-230.4, vis=3.0, pres=2.5
        rawOutput[0] = 128.0f;
        rawOutput[1] = 51.2f;
        rawOutput[2] = -230.4f;
        rawOutput[3] = 3.0f;
        rawOutput[4] = 2.5f;

        // Landmark 1 (LeftInnerEye): x=120, y=45.0, z=-220.0, vis=2.8, pres=2.2
        rawOutput[5] = 120.0f;
        rawOutput[6] = 45.0f;
        rawOutput[7] = -220.0f;
        rawOutput[8] = 2.8f;
        rawOutput[9] = 2.2f;

        // Landmark 2 (LeftEye): x=115, y=44.0, z=-225.0, vis=2.5, pres=2.0
        rawOutput[10] = 115.0f;
        rawOutput[11] = 44.0f;
        rawOutput[12] = -225.0f;
        rawOutput[13] = 2.5f;
        rawOutput[14] = 2.0f;

        // Landmark 11 (LeftShoulder): x=80, y=120, z=-100, vis=2.0, pres=1.8
        rawOutput[55] = 80.0f;
        rawOutput[56] = 120.0f;
        rawOutput[57] = -100.0f;
        rawOutput[58] = 2.0f;
        rawOutput[59] = 1.8f;

        // Landmark 12 (RightShoulder): x=176, y=118, z=-95, vis=2.2, pres=1.9
        rawOutput[60] = 176.0f;
        rawOutput[61] = 118.0f;
        rawOutput[62] = -95.0f;
        rawOutput[63] = 2.2f;
        rawOutput[64] = 1.9f;

        // Landmark 23 (LeftHip): x=100, y=200, z=-80, vis=1.5, pres=1.3
        rawOutput[115] = 100.0f;
        rawOutput[116] = 200.0f;
        rawOutput[117] = -80.0f;
        rawOutput[118] = 1.5f;
        rawOutput[119] = 1.3f;

        // Landmark 24 (RightHip): x=156, y=198, z=-78, vis=1.6, pres=1.4
        rawOutput[120] = 156.0f;
        rawOutput[121] = 198.0f;
        rawOutput[122] = -78.0f;
        rawOutput[123] = 1.6f;
        rawOutput[124] = 1.4f;

        return rawOutput;
    }
}
