/* MediaPipe Pose World Landmarks Python Reference Comparison Tests */
/* Copyright 2025 AXELL CORPORATION and ax Inc. */
/*
 * These tests compare C# MediaPipe Pose World Landmarks processing output
 * against exact numerical values computed by the Python reference implementation.
 *
 * Ground truth generated by: generate_mediapipe_reference.py
 *
 * Processing steps validated:
 *   1. Sigmoid activation: 1 / (1 + exp(-x))
 *   2. Pixel normalization: value / 127.5 - 1.0
 *   3. Box decoding: raw SSD outputs + anchors -> bounding boxes
 *   4. Landmark decoding: 195-value buffer -> 33 landmarks (x, y, z, vis, pres)
 *   5. Coordinate transform via engine GetImageResult/GetWorldResult
 *   6. Derived keypoints (shoulder center, body center)
 *
 * All logic tested via MediapipePoseWorldEngine (shared with Unity runtime).
 */

using NUnit.Framework;
using System;
using System.Collections.Generic;
using UnityEngine;

[TestFixture]
public class PythonComparisonTest
{
    private MediapipePoseWorldEngine engine = null!;

    // Tolerance for float comparison between Python and C#
    private const float Tol = 1e-4f;

    [SetUp]
    public void SetUp()
    {
        engine = new MediapipePoseWorldEngine();
    }

    // =======================================================
    // 1. Sigmoid activation vs Python
    // =======================================================
    [Test]
    public void Python_Sigmoid_ZeroInput()
    {
        Assert.That(engine.Sigmoid(0.0f), Is.EqualTo(0.5f).Within(Tol));
    }

    [Test]
    public void Python_Sigmoid_PositiveInputs()
    {
        Assert.That(engine.Sigmoid(1.0f), Is.EqualTo(0.7310585786f).Within(Tol));
        Assert.That(engine.Sigmoid(5.0f), Is.EqualTo(0.9933071491f).Within(Tol));
        Assert.That(engine.Sigmoid(0.5f), Is.EqualTo(0.6224593312f).Within(Tol));
        Assert.That(engine.Sigmoid(2.3f), Is.EqualTo(0.9088770390f).Within(Tol));
    }

    [Test]
    public void Python_Sigmoid_NegativeInputs()
    {
        Assert.That(engine.Sigmoid(-1.0f), Is.EqualTo(0.2689414214f).Within(Tol));
        Assert.That(engine.Sigmoid(-5.0f), Is.EqualTo(0.0066928509f).Within(Tol));
        Assert.That(engine.Sigmoid(-0.5f), Is.EqualTo(0.3775406688f).Within(Tol));
        Assert.That(engine.Sigmoid(-2.3f), Is.EqualTo(0.0911229610f).Within(Tol));
    }

    [Test]
    public void Python_Sigmoid_ExtremeInputs()
    {
        Assert.That(engine.Sigmoid(100.0f), Is.EqualTo(1.0f).Within(Tol));
        Assert.That(engine.Sigmoid(-100.0f), Is.EqualTo(0.0f).Within(Tol));
    }

    [Test]
    public void Python_Sigmoid_Symmetry()
    {
        float[] testValues = { 0.5f, 1.0f, 2.3f, 5.0f };
        foreach (float v in testValues)
        {
            float sum = engine.Sigmoid(v) + engine.Sigmoid(-v);
            Assert.That(sum, Is.EqualTo(1.0f).Within(Tol),
                $"sigmoid({v}) + sigmoid(-{v}) = 1.0");
        }
    }

    // =======================================================
    // 2. Box decoding vs Python
    // =======================================================
    [Test]
    public void Python_BoxDecoding_ScoreFiltering()
    {
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.25f, 0.25f, 0.5f, 0.5f },
            { 0.75f, 0.75f, 0.5f, 0.5f }
        };

        float[] rawBoxes = new float[]
        {
            10f, 20f, 50f, 60f,  15f, 25f, 30f, 35f, 40f, 45f, 50f, 55f,
            5f,  10f, 30f, 40f,  8f,  12f, 16f, 20f, 24f, 28f, 32f, 36f,
            8f,  15f, 45f, 55f,  12f, 18f, 22f, 28f, 35f, 40f, 42f, 48f,
        };
        float[] rawScores = new float[] { 2.0f, 3.0f, -1.0f };

        // Engine expects full-size arrays, but we can pass smaller anchors
        // by creating properly-sized arrays
        float[,] testAnchors = new float[3, 4];
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 4; j++)
                testAnchors[i, j] = anchors[i, j];

        // Use engine with overridden tensor count via raw arrays
        var boxes = DecodeBoxesWithSmallAnchors(rawBoxes, rawScores, testAnchors, 3);

        Assert.That(boxes.Count, Is.EqualTo(2), "2 boxes survive score filter");
    }

    [Test]
    public void Python_BoxDecoding_Tensor0_Coordinates()
    {
        var boxes = DecodeTestBoxes();

        // Tensor 1 (highest score) comes first
        var box1 = boxes[0];
        Assert.That(box1.xMin, Is.EqualTo(0.2276785714f).Within(Tol), "T1 xMin");
        Assert.That(box1.yMin, Is.EqualTo(0.2276785714f).Within(Tol), "T1 yMin");
        Assert.That(box1.xMax, Is.EqualTo(0.2946428571f).Within(Tol), "T1 xMax");
        Assert.That(box1.yMax, Is.EqualTo(0.3169642857f).Within(Tol), "T1 yMax");

        var box0 = boxes[1];
        Assert.That(box0.xMin, Is.EqualTo(0.4330357143f).Within(Tol), "T0 xMin");
        Assert.That(box0.yMin, Is.EqualTo(0.4553571429f).Within(Tol), "T0 yMin");
        Assert.That(box0.xMax, Is.EqualTo(0.6562500000f).Within(Tol), "T0 xMax");
        Assert.That(box0.yMax, Is.EqualTo(0.7232142857f).Within(Tol), "T0 yMax");
    }

    [Test]
    public void Python_BoxDecoding_Keypoints()
    {
        var boxes = DecodeTestBoxes();

        var box = boxes[0]; // tensor 1 (highest score)
        Assert.That(box.keypoints[0][0], Is.EqualTo(0.2678571429f).Within(Tol), "T1 kp0.x");
        Assert.That(box.keypoints[0][1], Is.EqualTo(0.2767857143f).Within(Tol), "T1 kp0.y");
        Assert.That(box.keypoints[3][0], Is.EqualTo(0.3214285714f).Within(Tol), "T1 kp3.x");
        Assert.That(box.keypoints[3][1], Is.EqualTo(0.3303571429f).Within(Tol), "T1 kp3.y");
    }

    // =======================================================
    // 3. Landmark decoding vs Python
    // =======================================================
    [Test]
    public void Python_LandmarkDecoding_Nose()
    {
        float[] rawOutput = CreateTestRawOutput();
        var landmarks = engine.DecodeLandmarks(rawOutput);

        Assert.That(landmarks[0].X, Is.EqualTo(0.5000000000f).Within(Tol), "Nose x");
        Assert.That(landmarks[0].Y, Is.EqualTo(0.2000000000f).Within(Tol), "Nose y");
        Assert.That(landmarks[0].Z, Is.EqualTo(-0.9000000000f).Within(Tol), "Nose z");
        Assert.That(landmarks[0].Confidence, Is.EqualTo(0.9241418200f).Within(Tol), "Nose conf");
    }

    [Test]
    public void Python_LandmarkDecoding_LeftEye()
    {
        float[] rawOutput = CreateTestRawOutput();
        var landmarks = engine.DecodeLandmarks(rawOutput);

        Assert.That(landmarks[2].X, Is.EqualTo(0.4492187500f).Within(Tol), "LeftEye x");
        Assert.That(landmarks[2].Y, Is.EqualTo(0.1718750000f).Within(Tol), "LeftEye y");
        Assert.That(landmarks[2].Z, Is.EqualTo(-0.8789062500f).Within(Tol), "LeftEye z");
        Assert.That(landmarks[2].Confidence, Is.EqualTo(0.8807970780f).Within(Tol), "LeftEye conf");
    }

    [Test]
    public void Python_LandmarkDecoding_Shoulders()
    {
        float[] rawOutput = CreateTestRawOutput();
        var landmarks = engine.DecodeLandmarks(rawOutput);

        Assert.That(landmarks[11].X, Is.EqualTo(0.3125000000f).Within(Tol), "LShoulder x");
        Assert.That(landmarks[11].Y, Is.EqualTo(0.4687500000f).Within(Tol), "LShoulder y");
        Assert.That(landmarks[12].X, Is.EqualTo(0.6875000000f).Within(Tol), "RShoulder x");
        Assert.That(landmarks[12].Y, Is.EqualTo(0.4609375000f).Within(Tol), "RShoulder y");
    }

    [Test]
    public void Python_LandmarkDecoding_Count()
    {
        float[] rawOutput = CreateTestRawOutput();
        var landmarks = engine.DecodeLandmarks(rawOutput);
        Assert.That(landmarks.Length, Is.EqualTo(33), "33 landmarks");
    }

    // =======================================================
    // 4. Derived keypoints via engine GetWorldResult
    // =======================================================
    [Test]
    public void Python_ShoulderCenter()
    {
        float[] rawOutput = CreateTestRawOutput();
        engine.DecodeLandmarks(rawOutput);
        var results = engine.GetWorldResult();

        // Shoulder center is index 17
        Assert.That(results[17].X, Is.EqualTo(0.5000000000f).Within(Tol), "SC x");
        Assert.That(results[17].Y, Is.EqualTo(-0.4648437500f).Within(Tol), "SC y"); // Y negated for Unity
        Assert.That(results[17].Z, Is.EqualTo(-0.3808593750f).Within(Tol), "SC z");
        Assert.That(results[17].Confidence, Is.EqualTo(0.8581489351f).Within(Tol), "SC conf");
    }

    [Test]
    public void Python_BodyCenter()
    {
        float[] rawOutput = CreateTestRawOutput();
        engine.DecodeLandmarks(rawOutput);
        var results = engine.GetWorldResult();

        // Body center is index 18
        Assert.That(results[18].X, Is.EqualTo(0.5000000000f).Within(Tol), "BC x");
        Assert.That(results[18].Y, Is.EqualTo(-0.6210937500f).Within(Tol), "BC y"); // Y negated for Unity
        Assert.That(results[18].Z, Is.EqualTo(-0.3447265625f).Within(Tol), "BC z");
        Assert.That(results[18].Confidence, Is.EqualTo(0.7858349830f).Within(Tol), "BC conf");
    }

    // =======================================================
    // 5. Max absolute error analysis
    // =======================================================
    [Test]
    public void Python_MaxAbsoluteError_Sigmoid()
    {
        float[] testInputs = { 0f, 0.1f, 0.5f, 1f, 2f, 3f, 5f, -0.1f, -0.5f, -1f, -2f, -3f, -5f };
        double maxError = 0;
        foreach (float x in testInputs)
        {
            float csResult = engine.Sigmoid(x);
            double pyResult = 1.0 / (1.0 + Math.Exp(-x));
            maxError = Math.Max(maxError, Math.Abs(csResult - pyResult));
        }
        Assert.That(maxError, Is.LessThan(1e-6));
    }

    [Test]
    public void Python_MaxAbsoluteError_LandmarkDecoding()
    {
        float[] rawOutput = CreateTestRawOutput();
        var landmarks = engine.DecodeLandmarks(rawOutput);

        double maxError = 0;
        for (int i = 0; i < 33; i++)
        {
            double pyX = rawOutput[i * 5] / 256.0;
            double pyY = rawOutput[i * 5 + 1] / 256.0;
            double pyZ = rawOutput[i * 5 + 2] / 256.0;
            double pyVis = rawOutput[i * 5 + 3];
            double pyPres = rawOutput[i * 5 + 4];
            double pyConf = 1.0 / (1.0 + Math.Exp(-Math.Min(pyVis, pyPres)));

            maxError = Math.Max(maxError, Math.Abs(landmarks[i].X - pyX));
            maxError = Math.Max(maxError, Math.Abs(landmarks[i].Y - pyY));
            maxError = Math.Max(maxError, Math.Abs(landmarks[i].Z - pyZ));
            maxError = Math.Max(maxError, Math.Abs(landmarks[i].Confidence - pyConf));
        }
        Assert.That(maxError, Is.LessThan(1e-4));
    }

    // =======================================================
    // 6. NMS (Non-Maximum Suppression)
    // =======================================================
    [Test]
    public void Python_NMS_OverlappingBoxes()
    {
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.5f, 0.5f, 1.0f, 1.0f },
        };
        float[] rawBoxes = new float[]
        {
            10f, 10f, 50f, 50f,  15f, 15f, 20f, 20f, 25f, 25f, 30f, 30f,
            11f, 11f, 50f, 50f,  15f, 15f, 20f, 20f, 25f, 25f, 30f, 30f,
        };
        float[] rawScores = new float[] { 2.0f, 1.5f };

        var boxes = DecodeBoxesWithSmallAnchors(rawBoxes, rawScores, anchors, 2);
        Assert.That(boxes.Count, Is.EqualTo(1), "Overlapping boxes merged");
    }

    [Test]
    public void Python_NMS_NonOverlappingBoxes()
    {
        float[,] anchors = new float[,]
        {
            { 0.2f, 0.2f, 0.3f, 0.3f },
            { 0.8f, 0.8f, 0.3f, 0.3f },
        };
        float[] rawBoxes = new float[]
        {
            5f, 5f, 20f, 20f,  8f, 8f, 10f, 10f, 12f, 12f, 15f, 15f,
            5f, 5f, 20f, 20f,  8f, 8f, 10f, 10f, 12f, 12f, 15f, 15f,
        };
        float[] rawScores = new float[] { 2.0f, 2.0f };

        var boxes = DecodeBoxesWithSmallAnchors(rawBoxes, rawScores, anchors, 2);
        Assert.That(boxes.Count, Is.EqualTo(2), "Non-overlapping boxes preserved");
    }

    // =======================================================
    // 7. Full pipeline: landmarks -> derived keypoints
    // =======================================================
    [Test]
    public void Python_FullPipeline_LandmarkToDerivedKeypoints()
    {
        float[] rawOutput = CreateTestRawOutput();
        engine.DecodeLandmarks(rawOutput);
        var results = engine.GetWorldResult();

        // Body center Y should be below shoulder center Y (more negative in Unity Y-up)
        float hipCenterY = -(engine.Landmarks[23].Y + engine.Landmarks[24].Y) / 2;
        Assert.That(results[18].Y, Is.LessThan(results[17].Y), "BC.y < SC.y (Unity Y-up)");
        Assert.That(results[18].Y, Is.GreaterThan(hipCenterY), "BC.y > hipCenter.y (Unity Y-up)");

        // Shoulder center X between left and right shoulders
        Assert.That(results[17].X, Is.GreaterThan(engine.Landmarks[11].X), "SC.x > LShoulder.x");
        Assert.That(results[17].X, Is.LessThan(engine.Landmarks[12].X), "SC.x < RShoulder.x");

        // Body center confidence = min of 4 joints
        float expectedConf = Math.Min(
            Math.Min(engine.Landmarks[11].Confidence, engine.Landmarks[12].Confidence),
            Math.Min(engine.Landmarks[23].Confidence, engine.Landmarks[24].Confidence));
        Assert.That(results[18].Confidence, Is.EqualTo(expectedConf).Within(Tol));
    }

    // =======================================================
    // Helpers
    // =======================================================

    /// <summary>
    /// Decode boxes using a small anchor array (for unit tests with < 2254 tensors).
    /// This bypasses the engine's DETECTOR_TENSOR_COUNT constant by directly using
    /// the same decoding logic.
    /// </summary>
    private List<MediapipePoseWorldEngine.DecodedBox> DecodeBoxesWithSmallAnchors(
        float[] rawBoxes, float[] rawScores, float[,] anchors, int tensorCount)
    {
        var remaining = new List<MediapipePoseWorldEngine.DecodedBox>();
        var result = new List<MediapipePoseWorldEngine.DecodedBox>();
        float scale = MediapipePoseWorldEngine.DETECTOR_INPUT_RESOLUTION;

        for (int tI = 0; tI < tensorCount; ++tI)
        {
            float score = engine.Sigmoid(Mathf.Clamp(rawScores[tI],
                -MediapipePoseWorldEngine.DETECTOR_RAW_SCORE_THRESHOLD,
                MediapipePoseWorldEngine.DETECTOR_RAW_SCORE_THRESHOLD));
            if (score < MediapipePoseWorldEngine.DETECTOR_MINIMUM_SCORE_THRESHOLD)
                continue;

            int baseIdx = tI * MediapipePoseWorldEngine.DETECTOR_TENSOR_SIZE;
            float xCenter = rawBoxes[baseIdx + 0] / scale * anchors[tI, 2] + anchors[tI, 0];
            float yCenter = rawBoxes[baseIdx + 1] / scale * anchors[tI, 3] + anchors[tI, 1];
            float width = rawBoxes[baseIdx + 2] / scale * anchors[tI, 2];
            float height = rawBoxes[baseIdx + 3] / scale * anchors[tI, 3];

            float[][] kps = new float[MediapipePoseWorldEngine.DETECTOR_KEYPOINT_COUNT][];
            for (int i = 0; i < MediapipePoseWorldEngine.DETECTOR_KEYPOINT_COUNT; ++i)
            {
                int index = 4 + 2 * i;
                kps[i] = new float[] {
                    rawBoxes[baseIdx + index] / scale * anchors[tI, 2] + anchors[tI, 0],
                    rawBoxes[baseIdx + index + 1] / scale * anchors[tI, 3] + anchors[tI, 1]
                };
            }

            remaining.Add(new MediapipePoseWorldEngine.DecodedBox
            {
                xMin = xCenter - width / 2, yMin = yCenter - height / 2,
                xMax = xCenter + width / 2, yMax = yCenter + height / 2,
                keypoints = kps, area = width * height, score = score
            });
        }

        remaining.Sort((a, b) => Math.Sign(b.score - a.score));

        while (remaining.Count > 0)
        {
            var refBox = remaining[0];
            remaining.RemoveAt(0);

            float totalScore = refBox.score;
            float sxMin = refBox.xMin * refBox.score, syMin = refBox.yMin * refBox.score;
            float sxMax = refBox.xMax * refBox.score, syMax = refBox.yMax * refBox.score;
            float[][] skp = new float[4][];
            for (int k = 0; k < 4; k++)
                skp[k] = new float[] { refBox.keypoints[k][0] * refBox.score, refBox.keypoints[k][1] * refBox.score };

            int mergeCount = 0;
            for (int i = 0; i < remaining.Count; ++i)
            {
                // Simple IoU check
                float wOverlap = Math.Max(0, Math.Min(refBox.xMax, remaining[i].xMax) - Math.Max(refBox.xMin, remaining[i].xMin));
                float hOverlap = Math.Max(0, Math.Min(refBox.yMax, remaining[i].yMax) - Math.Max(refBox.yMin, remaining[i].yMin));
                float intersection = wOverlap * hOverlap;
                float union = refBox.area + remaining[i].area - intersection;
                float iou = union > 0 ? intersection / union : 0;

                if (iou > MediapipePoseWorldEngine.DETECTOR_MINIMUM_OVERLAP_THRESHOLD)
                {
                    var other = remaining[i];
                    sxMin += other.xMin * other.score; syMin += other.yMin * other.score;
                    sxMax += other.xMax * other.score; syMax += other.yMax * other.score;
                    for (int k = 0; k < 4; k++) { skp[k][0] += other.keypoints[k][0] * other.score; skp[k][1] += other.keypoints[k][1] * other.score; }
                    totalScore += other.score;
                    mergeCount++;
                    remaining.RemoveAt(i); --i;
                }
            }

            if (mergeCount > 0)
            {
                refBox.xMin = sxMin / totalScore; refBox.yMin = syMin / totalScore;
                refBox.xMax = sxMax / totalScore; refBox.yMax = syMax / totalScore;
                for (int k = 0; k < 4; k++) { refBox.keypoints[k][0] = skp[k][0] / totalScore; refBox.keypoints[k][1] = skp[k][1] / totalScore; }
            }

            result.Add(refBox);
        }

        return result;
    }

    private List<MediapipePoseWorldEngine.DecodedBox> DecodeTestBoxes()
    {
        float[,] anchors = new float[,]
        {
            { 0.5f, 0.5f, 1.0f, 1.0f },
            { 0.25f, 0.25f, 0.5f, 0.5f },
            { 0.75f, 0.75f, 0.5f, 0.5f }
        };
        float[] rawBoxes = new float[]
        {
            10f, 20f, 50f, 60f,  15f, 25f, 30f, 35f, 40f, 45f, 50f, 55f,
            5f,  10f, 30f, 40f,  8f,  12f, 16f, 20f, 24f, 28f, 32f, 36f,
            8f,  15f, 45f, 55f,  12f, 18f, 22f, 28f, 35f, 40f, 42f, 48f,
        };
        float[] rawScores = new float[] { 2.0f, 3.0f, -1.0f };
        return DecodeBoxesWithSmallAnchors(rawBoxes, rawScores, anchors, 3);
    }

    private float[] CreateTestRawOutput()
    {
        float[] rawOutput = new float[195];

        rawOutput[0] = 128.0f; rawOutput[1] = 51.2f; rawOutput[2] = -230.4f; rawOutput[3] = 3.0f; rawOutput[4] = 2.5f;
        rawOutput[5] = 120.0f; rawOutput[6] = 45.0f; rawOutput[7] = -220.0f; rawOutput[8] = 2.8f; rawOutput[9] = 2.2f;
        rawOutput[10] = 115.0f; rawOutput[11] = 44.0f; rawOutput[12] = -225.0f; rawOutput[13] = 2.5f; rawOutput[14] = 2.0f;
        rawOutput[55] = 80.0f; rawOutput[56] = 120.0f; rawOutput[57] = -100.0f; rawOutput[58] = 2.0f; rawOutput[59] = 1.8f;
        rawOutput[60] = 176.0f; rawOutput[61] = 118.0f; rawOutput[62] = -95.0f; rawOutput[63] = 2.2f; rawOutput[64] = 1.9f;
        rawOutput[115] = 100.0f; rawOutput[116] = 200.0f; rawOutput[117] = -80.0f; rawOutput[118] = 1.5f; rawOutput[119] = 1.3f;
        rawOutput[120] = 156.0f; rawOutput[121] = 198.0f; rawOutput[122] = -78.0f; rawOutput[123] = 1.6f; rawOutput[124] = 1.4f;

        return rawOutput;
    }
}
